activation_dropout: 0.1
attention_dropout: 0.0
classifier_dropout: 0.4
d_model: 128
decoder_attention_heads: 16
decoder_ffn_dim: 256
decoder_layerdrop: 0.2
decoder_layers: 2
dropout: 0.0
encoder_attention_heads: 16
encoder_ffn_dim: 256
encoder_layerdrop: 0.2
encoder_layers: 2
joint_idx:
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 71
  - 72
  - 73
  - 74
max_position_embeddings: 256
num_labels: 100
